version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - http-server

  http-server:
    build: http-server
    depends_on:
      - elastic
    environment:
      - ESHOST=elastic
      - SCIMEDVER=${COMMIT}
    volumes:
      - ./http-server/conf:/usr/local/conf

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
    env_file:
      - ./elasticsearch-data/.env

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
      - SERVER_BASEPATH=/kibana
      - SERVER_REWRITEBASEPATH=true 
    depends_on:
      - elastic

  twitter-updater:
    build: download/autoupdate
    depends_on:
      - elastic
    environment:
      - ESHOST=elastic
    volumes:
      - ./download/autoupdate/data:/usr/local/data
