extra_annotations = \
{
'ai':       [   'artificial intelligence', 'machine learning', 'statistical learning', 'statistical model', 'supervised model',
                'unsupervised model', 'computer vision', 'image analysis', 'object recognistion', 'object detection',
                'image segmentation', 'deep learning', 'cognitive computing', 'neural network', 'classification model',
                'regression model', 'classifier', 'reinforcment learning'   ],

'tech':     [   'digital health', 'ehealth', 'digital medicine', 'mhealth', 'digital healthcare', 'digital biomarker', 'telemedicine'   ],

'medicine': [   'health occupations', 'health occupation', 'health professions', 'health profession', 'profession, health',
                'professions, health', 'health occup', 'medicine', 'medical specialities', 'medical speciality', 'speciality, medical',
                'specialities, medical', 'specialties, medical', 'medical specialty', 'specialty, medical', 'medical specialties',
                'med specialties', 'med specialty', 'specialty med', 'specialties med', 'med specialities', 'specialities med',
                'addiction psychiatry', 'psychiatry, addiction', 'addiction medicine', 'medicine, addiction', 'adolescent medicine',
                'medicine, adolescent', 'hebiatrics', 'ephebiatrics', 'med adolescent', 'adolescent med', 'aerospace medicine',
                'medicine, aerospace', 'med aerospace', 'aerospace med', 'aviation medicine', 'medicine, aviation', 'med aviation',
                'aviation med', 'medicine, space', 'space medicine', 'med space', 'space med', 'allergy specialty', 'specialty, allergy',
                'allergy and immunology', 'allergy, immunology', 'immunology, allergy', 'allergy immunology', 'immunology allergy',
                'immunology and allergy', 'allergy immunol', 'immunol allergy', 'immunology', 'immunol', 'immunochemistry', 'immunochem',
                'anesthesiology', 'anesthesiol', 'bariatric medicine', 'medicine, bariatric', 'behavioral medicine',
                'medicine, behavioral', 'med behavioral', 'behavioral med', 'health psychology', 'health psychologies',
                'psychologies, health', 'psychology, health', 'health psychol', 'psychol health', 'clinical medicine',
                'medicine, clinical', 'clin med', 'med clin', 'evidence-based medicine', 'evidence based medicine',
                'medicine, evidence based', 'medicine, evidence-based', 'evidence based med', 'med evidence based', 'precision medicine',
                'medicine, precision', 'p health', 'p-health', 'p-healths', 'personalized medicine', 'medicine, personalized',
                'individualized medicine', 'medicine, individualized', 'community medicine', 'medicine, community', 'med community',
                'community med', 'dermatology', 'dermatol', 'disaster medicine', 'medicine, disaster', 'emergency medicine',
                'medicine, emergency', 'med emergency', 'emergency med', 'emergency medicine, pediatric', 'medicine, pediatric emergency',
                'pediatric emergency medicine', 'forensic medicine', 'medicine, forensic', 'med forensic', 'forensic med',
                'medicine, legal', 'legal medicine', 'legal med', 'med legal', 'forensic genetics', 'genetics, forensic',
                'genetic, forensic', 'forensic genetic', 'forensic pathology', 'pathology, forensic', 'forensic pathol', 'pathol forensic',
                'general practice', 'practice, general', 'family practice', 'family practices', 'practices, family', 'practice, family',
                'genetics, medical', 'medical genetics', 'med genet', 'genet med', 'geography, medical', 'medical geography',
                'geomedicine', 'nosogeography', 'geogr med', 'med geogr', 'topography, medical', 'medical topography', 'med topogr',
                'topogr med', 'geriatrics', 'gerontology', 'gerontol', 'international health problems', 'health problem, international',
                'international health problem', 'problem, international health', 'health problems, international',
                'problems, international health', 'world health', 'health, world', 'worldwide health', 'health, worldwide',
                'healths, international', 'international healths', 'international health', 'health, international', 'global health',
                'health, global', 'hospital medicine', 'medicine, hospital', 'integrative medicine', 'medicine, integrative',
                'internal medicine', 'medicine, internal', 'internal med', 'med internal', 'cardiology', 'cardiol', 'vascular medicine',
                'medicine, vascular', 'angiology', 'cardiovascular disease specialty', 'disease specialty, cardiovascular',
                'specialty, cardiovascular disease', 'endocrinology', 'endocrinol', 'endocrinology and metabolism specialty',
                'metabolism and endocrinology specialty', 'gastroenterology', 'gastroenterol', 'hepatology', 'hepatol', 'hematology',
                'hematol', 'infectious disease medicine', 'disease medicine, infectious', 'medicine, infectious disease',
                'infectious diseases specialty', 'infectious disease specialties', 'infectious disease specialty',
                'infectious diseases specialties', 'specialties, infectious diseases', 'specialties, infectious disease',
                'specialty, infectious disease', 'diseases specialty, infectious', 'specialty, infectious diseases', 'medical oncology',
                'oncology, medical', 'med oncol', 'oncol med', 'clinical oncology', 'oncology, clinical', 'nephrology', 'nephrol',
                'pulmonary medicine', 'medicine, pulmonary', 'pneumology', 'pneumonology', 'pulmonology', 'med pulm', 'pulm med',
                'pneumonol', 'pneumol', 'pulmonol', 'respiratory medicine', 'medicine, respiratory', 'rheumatology', 'rheumatol',
                'sleep medicine specialty', 'medicine specialties, sleep', 'sleep medicine specialties', 'specialties, sleep medicine',
                'medicine specialty, sleep', 'specialty, sleep medicine', 'military medicine', 'medicine, military', 'med military',
                'military med', 'molecular medicine', 'medicines, molecular', 'molecular medicines', 'medicine, molecular',
                'naval medicine', 'medicine, naval', 'nautical medicine', 'medicine, nautical', 'med nautical', 'nautical med',
                'med naval', 'naval med', 'submarine medicine', 'medicine, submarine', 'med submarine', 'submarine med', 'neurology',
                'neurol', 'neuropathologist', 'neuropathologists', 'neuropathology', 'neuropathologies', 'neurotology', 'neuro-otology',
                'neuro otology', 'otoneurology', 'osteopathic medicine', 'medicine, osteopathic', 'med osteopathic', 'osteopathic med',
                'osteopathic manipulative medicine', 'manipulative medicine, osteopathic', 'medicine, osteopathic manipulative',
                'palliative medicine', 'medicine, palliative', 'palliative care medicine', 'medicine, palliative care', 'med palliative',
                'palliative med', 'pathology', 'pathologies', 'pathol', 'forensic pathology', 'pathology, forensic', 'forensic pathol',
                'pathol forensic', 'neuropathologist', 'neuropathologists', 'neuropathology', 'neuropathologies', 'pathology, clinical',
                'clinical pathology', 'clin pathol', 'pathol clin', 'pathology, molecular', 'molecular pathologies',
                'pathologies, molecular', 'molecular pathology', 'molecular diagnostics', 'diagnostic, molecular', 'molecular diagnostic',
                'diagnostics, molecular', 'diagnostic molecular pathology', 'diagnostic molecular pathologies',
                'molecular pathologies, diagnostic', 'pathologies, diagnostic molecular', 'molecular pathology, diagnostic',
                'pathology, diagnostic molecular', 'pathology, surgical', 'surgical pathology', 'pathol surg', 'surg pathol',
                'telepathology', 'telepathol', 'pediatrics', 'neonatology', 'neonatol', 'emergency medicine, pediatric',
                'medicine, pediatric emergency', 'pediatric emergency medicine', 'perinatology', 'perinatol', 'perioperative medicine',
                'medicine, perioperative', 'physical and rehabilitation medicine', 'physical medicine and rehabilitation',
                'physical medicine', 'medicine, physical', 'physiatry', 'physiatrics', 'med physical', 'physical med', 'habilitation',
                'rehabilitation', 'rehabil', 'psychiatrist', 'psychiatrists', 'psychiatry', 'adolescent psychiatry',
                'psychiatry, adolescent', 'biological psychiatry', 'psychiatry, biological', 'biologic psychiatry', 'psychiatry, biologic',
                'psychiatry biol', 'biol psychiatry', 'child psychiatry', 'psychiatry, child', 'community psychiatry',
                'psychiatry, community', 'social psychiatry', 'psychiatry, social', 'forensic psychiatry', 'psychiatry, forensic',
                'jurisprudence, psychiatric', 'psychiatric jurisprudence', 'geriatric psychiatry', 'psychiatry, geriatric',
                'psychogeriatrics', 'military psychiatry', 'psychiatry, military', 'neuropsychiatry',
                'environment, preventive medicine and public health', 'environment, preventive medicine & public health',
                'envir prev med public health', 'public health', 'health, public', 'community health', 'health, community', 'epidemiology',
                'epidemiol', 'preventive medicine', 'medicine, preventive', 'preventative medicine', 'medicine, preventative', 'med prev',
                'prev med', 'preventive care', 'care, preventive', 'preventative care', 'care, preventative', 'radiology', 'radiol',
                'atomic medicine', 'medicine, atomic', 'nuclear medicine', 'medicine, nuclear', 'med atomic', 'atomic med', 'med nuclear',
                'nuclear med', 'radiology, nuclear', 'nuclear radiology', 'nuclear radiol', 'radiol nuclear', 'therapeutic radiology',
                'radiology, therapeutic', 'radiol ther', 'ther radiol', 'radiation oncology', 'oncology, radiation', 'oncol rad',
                'rad oncol', 'radiology, interventional', 'interventional radiology', 'interventional radiol', 'radiol interventional',
                'regenerative medicine', 'regenerative medicines', 'medicines, regenerative', 'medicine, regenerative', 'regenerative med',
                'reproductive medicine', 'medicine, reproductive', 'med reproductive', 'reproductive med', 'andrology', 'androl',
                'gynecology', 'gynecol', 'social medicine', 'medicine, social', 'med social', 'social med', 'specialties, surgical',
                'surgical specialties', 'specialties surg', 'surg specialties', 'colon and rectal surgery specialty',
                'surgery specialty, colon and rectal', 'colorectal surgery', 'surgery, colorectal', 'surg specialty colon rectal',
                'colon rectal surg specialty', 'colorectal surg', 'surg colorectal', 'colon surgery specialty', 'specialty, colon surgery',
                'surgery specialty, colon', 'specialty colon surg', 'surg specialty colon', 'colon surg specialty', 'proctology',
                'rectal surgery specialty', 'specialty, rectal surgery', 'surgery specialty, rectal', 'rectal surg specialty',
                'specialty rectal surg', 'surg specialty rectal', 'proctol', 'surgery', 'general surgery', 'surgery, general', 'surg',
                'gynecology', 'gynecol', 'neurosurgery', 'neurosurgeries', 'neurosurg', 'obstetrics', 'ophthalmology', 'ophthalmol',
                'orthognathic surgery', 'orthognathic surgeries', 'surgeries, orthognathic', 'surgery, orthognathic', 'orthopedics',
                'otolaryngology', 'otorhinolaryngology', 'otolaryngol', 'otorhinolaryngol', 'otology', 'otol', 'laryngology',
                'surgery, plastic', 'plastic surgery', 'plastic surg', 'surg plastic', 'surgery, cosmetic', 'cosmetic surgery',
                'surg cosmetic', 'cosmetic surg', 'esthetic surgery', 'esthetic surgeries', 'surgeries, esthetic', 'surgery, esthetic',
                'esthetic surg', 'surg esthetic', 'surgical oncology', 'oncology, surgical', 'thoracic surgery', 'surgery, thoracic',
                'surg thoracic', 'thoracic surg', 'surgery, cardiac', 'cardiac surgery', 'heart surgery', 'surgery, heart', 'surg cardiac',
                'cardiac surg', 'surg heart', 'heart surg', 'traumatology', 'traumatol', 'surgical traumatology', 'traumatology, surgical',
                'urology', 'urol', 'sports medicine', 'medicine, sport', 'sport medicine', 'medicine, sports', 'med sports', 'med sport',
                'sport med', 'sports med', 'sports nutritional sciences', 'nutritional science, sports', 'science, sports nutritional',
                'sports nutritional science', 'nutritional sciences, sports', 'sciences, sports nutritional', 'sports nutrition sciences',
                'nutrition science, sports', 'science, sports nutrition', 'sports nutrition science', 'nutrition sciences, sports',
                'sciences, sports nutrition', 'exercise nutritional sciences', 'exercise nutritional science',
                'nutritional science, exercise', 'science, exercise nutritional', 'nutritional sciences, exercise',
                'sciences, exercise nutritional', 'veterinary sports medicine', 'sports medicines, veterinary',
                'medicine, sports veterinary', 'medicine, veterinary sports', 'sports medicine, veterinary', 'sports veterinary medicine',
                'veterinary medicine, sports', 'telemedicine', 'telemed', 'telehealth', 'ehealth', 'mobile health', 'health, mobile',
                'mhealth', 'telepathology', 'telepathol', 'teleradiology', 'teleradiol', 'telerehabilitation', 'remote rehabilitation',
                'rehabilitations, remote', 'remote rehabilitations', 'rehabilitation, remote', 'telerehabilitations',
                'virtual rehabilitation', 'rehabilitations, virtual', 'virtual rehabilitations', 'rehabilitation, virtual',
                'tele-rehabilitation', 'tele rehabilitation', 'tele-rehabilitations', 'theranostic nanomedicine',
                'nanomedicines, theranostic', 'theranostic nanomedicines', 'nanomedicine, theranostic', 'theranostics', 'theranostic',
                'emporiatrics', 'travel medicine', 'medicine, travel', 'medicine, emporiatric', 'emporiatric medicine',
                'tropical medicine', 'medicine, tropical', 'med tropical', 'tropical med', 'vaccinology', 'venereology', 'venereol',
                'wilderness medicine', 'medicine, wilderness'   ],
}
